galaxy_info:
  author: 'Lucian Curteanu'
  namespace: lucian
  role_name: security
  description: 'Ansible role for security configurations'
  company: 'https://luciancurteanu.com'
  license: 'MIT'
  min_ansible_version: '2.9'

  platforms:
    - name: EL
      versions:
        - '9'

  galaxy_tags:
    - vps
    - security
    - hardening

dependencies: []
