galaxy_info:
  author: 'Lucian Curteanu'
  namespace: lucian
  role_name: nginx
  description: 'Ansible role to install and configure Nginx'
  company: 'https://luciancurteanu.com'
  license: 'MIT'
  min_ansible_version: '2.9'

  platforms:
    - name: EL
      versions:
        - '9'

  galaxy_tags:
    - web
    - server
    - http
    - https
    - nginx
    - vps

dependencies: []
  # - role: common # Example: uncomment if Nginx role depends on the common role
