---
- name: Verify
  hosts: all
  become: true
  gather_facts: true # Ensure facts are gathered for verification
  tasks:
    - name: Include mariadb role to verify its state
      ansible.builtin.include_role:
        name: mariadb
# ... any other verification tasks you might add later
