---
# Default variables for Nginx role

# Nginx version and repository settings
nginx_mainline: true

# System settings
nginx_nofile_limit: 65536
nginx_worker_connections: 20480

# Performance tuning
nginx_client_body_timeout: "10s"
nginx_send_timeout: "2s"
nginx_keepalive_timeout: "30s"
nginx_keepalive_requests: 10000
nginx_client_body_buffer_size: "128k"
nginx_client_header_buffer_size: "32k"
nginx_large_client_header_buffers: "8 64k"
nginx_client_header_timeout: "3m"
nginx_types_hash_max_size: 2048
nginx_client_max_body_size: "500M"

# Gzip settings
nginx_gzip: "on"
nginx_gzip_comp_level: 6
nginx_gzip_buffers: "16 8k"

# Cache settings
nginx_cache_dir: /etc/nginx/cache