---
dependencies: []

galaxy_info:
  author: 'Lucian Curteanu'
  namespace: lucian
  role_name: cockpit
  description: 'Install and configure Cockpit web-based server management interface'
  company: ''
  license: 'MIT'
  min_ansible_version: '2.9'
  platforms:
    - name: EL
      versions:
        - '9'
  galaxy_tags:
    - cockpit
    - monitoring
    - management
    - web
