---
# Cockpit handlers

- name: Restart cockpit
  ansible.builtin.systemd:
    name: Cockpit.socket
    state: restarted

- name: Reload nginx
  ansible.builtin.systemd:
    name: Nginx
    state: reloaded

- name: Save iptables rules
  ansible.builtin.shell: iptables-save > /etc/sysconfig/iptables
  changed_when: false
