---
driver:
  name: Docker
platforms:
  - name: Almalinux9
    image: dokken/almalinux-9
    privileged: true
    command: /usr/sbin/init
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    tmpfs:
      - /run
      - /tmp
    security_opts:
      - "seccomp=unconfined"
    cgroupns_mode: "host"
    stop_signal: "SIGRTMIN+3"
provisioner:
  name: Ansible
  env:
    ANSIBLE_LOG_PATH: ansible_molecule_output.log
    PY_COLORS: '1'
    ANSIBLE_FORCE_COLOR: '1'
  config_options:
    defaults:
      result_format: yaml
  ansible_args: []
  playbooks:
    converge: converge.yml
verifier:
  name: Ansible
