---
- name: Verify GoProxy Role
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Include goproxy role to verify its state
      ansible.builtin.include_role:
        name: Goproxy
