---
driver:
  name: docker
platforms:
  - name: almalinux9
    image: dokken/almalinux-9
    privileged: true
    command: /usr/sbin/init
    pre_build_image: false
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    tmpfs:
      - /run
      - /tmp
    security_opts:
      - "seccomp=unconfined"
    cgroupns_mode: "host"
    stop_signal: "SIGRTMIN+3"
provisioner:
  name: ansible
  env:
    ANSIBLE_LOG_PATH: ansible_molecule_output.log
    PY_COLORS: '1'
    ANSIBLE_FORCE_COLOR: '1'
  config_options:
    defaults:
      result_format: yaml
  ansible_args: []
  inventory:
    links:
      group_vars: ../../../../inventory/group_vars/  # Path to your group_vars directory
  playbooks:
    converge: converge.yml
verifier:
  name: ansible
