---
# GoProxy role: Handlers

- name: Restart tor
  ansible.builtin.service:
    name: tor
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart goproxy
  ansible.builtin.service:
    name: goproxy
    state: restarted
