---
# Security role: Handlers

- name: Restart iptables
  ansible.builtin.service:
    name: Iptables
    state: restarted
  when: ansible_virtualization_type | default('') != 'docker'

- name: Restart ip6tables
  ansible.builtin.service:
    name: Ip6tables
    state: restarted
  when: ansible_virtualization_type | default('') != 'docker'

- name: Restart fail2ban
  ansible.builtin.service:
    name: Fail2ban
    state: restarted
