---
# handlers file for php
- name: Restart php-fpm
  ansible.builtin.systemd:
    name: "php-fpm.service"
    state: restarted
  when: ansible_service_mgr == 'systemd'
  listen: "Restart php-fpm" # Ensure this listen topic is unique if other roles might also want to restart a generic php-fpm
